framework:
    workflows:
        document_publishing:
            type: state_machine
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Document
            initial_marking: draft
            places:
                - draft
                - review
                - published
                - archived
            transitions:
                to_review:
                    from: draft
                    to: review
                to_publish:
                    from: review
                    to: published
                to_archive:
                    from: [draft, review, published]
                    to: archived